update the release script

diff --git a/release b/release
--- a/release
+++ b/release
@@ -12,6 +12,17 @@ TWINE_USERNAME=$PYPI_USERNAME
 
 export FLIT_USERNAME TWINE_USERNAME
 
+if ! bumpversion -h &> /dev/null; then
+	echo "Missing bumpversion! Please run: pip3 install -U -r requirements-dev.txt"
+	exit 1
+fi
+
+if ! twine -h &> /dev/null; then
+	echo "Missing twine! Please run: pip3 install -U -r requirements-dev.txt"
+	exit 1
+fi
+
+# Bump the version, tag, and push
 rm -f dist/*
 bumpversion patch
 git push origin master --tags
